### ISSUE TITLE
Bug Report: Compiling error

### ISSUE THREAD

**Issue by Similirity** [Leather128/LeatherEngine#19]
I try to compile the source code and I keep getting this error:

source/modding/PolymodHandler.hx:14: lines 14-28 : { modRoot : String, frameworkParams : { assetLibraryPaths : haxe.ds.Map<String, String> }, errorCallback : Null<(error : polymod.PolymodError) -> V... has extra field frameworkParams

source/modding/PolymodHandler.hx:14: lines 14-28 : For function argument 'params'

I'm not sure how to fix this.

I have a 64-bit Windows processor.

**Comment by Leather128** [comment]
run the command `haxelib update polymod` or `haxelib git polymod https://github.com/larsiusprime/polymod.git` to update your version of polymod, the issue is because older versions of polymod work differently and to get the newer versions to work, i had to add that parameter. basically just run either of those commands you you should be fine.

**Comment by Similirity** [comment]
yo thank you so much!
