### ISSUE TITLE
freeplay with mods enabled and pause menu crashes

### ISSUE THREAD

**Issue by theloser7455** [Leather128/LeatherEngine#37]
i used 0.3.7 version
and my game crashes when i enabled mods and go to freeplay the game crashes and the game also crashes when i pause while in a song
and when i die and press backspace to go freeplay the game also crashes and when i go to the options menu with mods enabled the game also crashes
i tried this with all optimisations enabled
but without antialiasing and health icons and menu background the crashes are gone can you please fix this?

**Comment by Leather128** [comment]
Question: How much RAM / Memory do you have?

**Comment by theloser7455** [comment]
i forgot

**Comment by Leather128** [comment]
you can check with task manager you know

**Comment by Leather128** [comment]
![image](https://user-images.githubusercontent.com/81660872/141381147-e8f7ff65-82c0-4f0e-8489-0027754461e8.png)

**Comment by theloser7455** [comment]
i have 3,8 (4.0 gbs) memory

**Comment by Leather128** [comment]
That may be an issue since the game regularly can use 200-800 mbs of memory in regular stages, so this may be more of a hardware issue, obviously turning on optimizations helped (because it uses much much less memory), but there isn't much of a solution currently because the engine is already pretty optimized (to the point where I would have to rework tons of things to get it running better).

So basically for now, I do not have a fix but maybe in the future I can figure out a way to fix this.
