### ISSUE TITLE
Enhancement(s): Charter improvements + arrows colored by timing

### ISSUE THREAD

**Issue by daisukidaisy** [Leather128/LeatherEngine#42]
### Charter improvements
Basically, allowing arrows to snap to units other than 16ths, so you don't need to hold Shift and guess.
### Arrows colored by timing
Instead of simply having one color per direction, arrows are colored based on their place on the chart.
Colors from StepMania are as follows:
- 4ths: red
- 8ths: blue
- 16ths: yellow
- 32nds: orange
- 64ths: green
- 12ths: purple
- 24ths: pink
- 48ths: light blue
- 192nds: white but I doubt you can see them since 192nds are the definition of a rhythm game joke
- Others: gray

**Comment by Leather128** [comment]
Seems like a good idea for the revamped charter that's coming in the future (that will have time signatures as well), and I may make the colored arrows an option (I know Kade Engine Has It) I'm just not sure how I would implement it yet, but if I could get it working it would be a nice thing to have.

**Comment by flowerbearttv** [comment]
> Seems like a good idea for the revamped charter that's coming in the future (that will have time signatures as well), and I may make the colored arrows an option (I know Kade Engine Has It) I'm just not sure how I would implement it yet, but if I could get it working it would be a nice thing to have.

if anything i want the beatsnap

**Comment by Leather128** [comment]
Commit [#c4b53a9](https://github.com/Leather128/LeatherEngine/commit/c4b53a947783ccc66567bc1e4b06c78de474bc4f) adds the note snapping, no not quanitization colors right now though, because of the 4 different arrow shapes (basically I would need to make 100 different sprites for all the note colors lmao, then times that by 3 for the different animations for all the notes and it might become a bit much)
